// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SSO.BO.Entities
{
    public partial class User
    {
        public User()
        {
            LoginTypeCreatedByUser = new HashSet<LoginType>();
            LoginTypeModifiedByUser = new HashSet<LoginType>();
            UserProfile = new HashSet<UserProfile>();
            UserTypeCreatedByUser = new HashSet<UserType>();
            UserTypeModifiedByUser = new HashSet<UserType>();
        }

        public Guid Id { get; set; }
        public Guid? UserRequestId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public bool EmailComfirmed { get; set; }
        public DateTime? EmailComfirmedDate { get; set; }
        public string Phone { get; set; }
        public bool PhoneComfirmed { get; set; }
        public DateTime? PhoneComfirmedDate { get; set; }
        public byte[] PasswordSalt { get; set; }
        public byte[] PasswordHash { get; set; }
        public bool ChangePwdNextLogin { get; set; }
        public DateTime? LastPwdChanged { get; set; }
        public string DeviceId { get; set; }
        public string Token { get; set; }
        public short LoginTypeId { get; set; }
        public short UserTypeId { get; set; }
        public Guid? ParentId { get; set; }
        public string DisplayName { get; set; }
        public bool Locked { get; set; }
        public DateTime? LockedDate { get; set; }
        public DateTime? LastAccessDate { get; set; }
        public string LastLoginIpAddress { get; set; }
        public DateTime CreatedDate { get; set; }
        public Guid? CreatedByUserId { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public Guid? ModifiedByUserId { get; set; }
        public string PictureProfile { get; set; }

        public virtual LoginType LoginType { get; set; }
        public virtual UserType UserType { get; set; }
        public virtual ICollection<LoginType> LoginTypeCreatedByUser { get; set; }
        public virtual ICollection<LoginType> LoginTypeModifiedByUser { get; set; }
        public virtual ICollection<UserProfile> UserProfile { get; set; }
        public virtual ICollection<UserType> UserTypeCreatedByUser { get; set; }
        public virtual ICollection<UserType> UserTypeModifiedByUser { get; set; }
    }
}